### ISSUE TITLE
Menu Output

### ISSUE THREAD

**Issue by Ryuuzei** [CISOS-Team/CISOS#18]
Ouput_menu.html and menu.css should be reviewed by all members

**Comment by Zeruxky** [comment]
Looking good. Only for the first stable release the stylesheet must be change:
- Font: Open Sans  (for united look) --> See other files
- Folder structure must be change. 
-- All html-files come in the folder home/html/...
-- All img-files come in the folder home/img/... 
-- The css-files come in the folder home/...
-- PHP-Files come in the folder home/html/php/....
It's not a necessary point, but it's quite easier to host the files on a webserver and it looks more structure.
But the folder structure can be changed anytime. You must only look at the link to the right folders.

**Comment by Ryuuzei** [comment]
Done can be closed?

**Comment by Zeruxky** [comment]
yes
