### ISSUE TITLE
Login - Page

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS#7]
Login Page with a formular. The formular should have:
- an input for username
- an input for password
- two checkboxes for save or not save the session (see --> https://wiki.selfhtml.org/wiki/JavaScript/Anwendung_und_Praxis/cookies)
- a button for send the formular

**Comment by Zeruxky** [comment]
Must reviewed by all members of CISOS

**Comment by Ryuuzei** [comment]
Wouldn't be one checkbox enough for saving the session
Example:
If the User selects the box then it saves the session
If it isn't selected then it doesn't.

**Comment by Zeruxky** [comment]
Okay.

**Comment by Ryuuzei** [comment]
yes
