### ISSUE TITLE
User configuration

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS#9]
We should provide an option for the user, to configurate the CISOS-System at his own. Maybe we could create a page, where the user can pick his own color (https://wiki.selfhtml.org/wiki/HTML/Formulare/input/Farbw%C3%A4hler), include his own logo and so on.

But this is a optional thing and should be forced at the end of this project.

**Comment by Ryuuzei** [comment]
I don't think it's not important at the moment and  we should think later about this

**Comment by Zeruxky** [comment]
Yeah, this is a optional thing. Can be closed.
